# Glide: https://github.com/bumptech/glide/blob/gh-pages/_config.yml
# Source repo: https://github.com/bruth/jekyll-docs-template
#Â Source site: http://bruth.github.io/jekyll-docs-template/
# Ref guide: https://visualstudiomagazine.com/Articles/2015/03/01/GitHub-Pages.aspx?Page=2

# Used by us
title: Transcoder
color: '#f8f8f8'
description: A well documented Android library providing hardware-accelerated video transcoding, using MediaCodec APIs instead of native code (no FFMPEG patent issues). Supports cropping to any dimension, concatenation, clipping, audio processing, video speed and much more. # used by ourselves and by seo tag.
disqus_shortname: 'natario1-transcoder'
google_analytics_id: 'UA-155077779-2'
google_site_verification: '4x49i17ABIrSvUl52SeL0-t0341aTnWWaC62-FYCRT4'
github: [metadata] # TODO What's this?
github_repo: Transcoder
github_version: 0.10.4
github_branch: main
baseurl: '/Transcoder' # Keep as an empty string if served up at the root
collections:
  about:
    name: Overview
    output: true
  docs:
    name: Documentation
    output: true
  extra:
    name: More
    output: true
screenshots:
  - 'screenshot-1.png'
  - 'screenshot-2.png'

# Jekyll specific stuff
author:
  name: Mattia Iavarone # Should appear in <head>.
  email: mat.iavarone@gmail.com
  github: natario1
  website: https://natario.dev
plugins:
  - jekyll-seo-tag # Add SEO tags
permalink: /:categories/:title # Ensure permalinks have no date nor extension
exclude: ['script', 'README.md'] # Exclude non-site files
highlighter: rouge # Syntax highlighting
markdown: kramdown # Use the kramdown Markdown renderer
kramdown:
  input: GFM # Use Github Flavored Markdown